# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Intefaz.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSlot


class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        self.setupUi(self)
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(853, 606)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sasasas = QtWidgets.QTabWidget(self.centralwidget)
        self.sasasas.setGeometry(QtCore.QRect(40, 20, 781, 531))
        self.sasasas.setObjectName("sasasas")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableView = QtWidgets.QTableView(self.tab)
        self.tableView.setGeometry(QtCore.QRect(50, 40, 441, 261))
        self.tableView.setObjectName("tableView")
        self.sasasas.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_3)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 42, 381, 181))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.IPlabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.IPlabel.setObjectName("IPlabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.IPlabel)
        self.IPtextEdit = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.IPtextEdit.setObjectName("IPtextEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.IPtextEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.Portlabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.Portlabel.setObjectName("Portlabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Portlabel)
        self.PorttextEdit = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.PorttextEdit.setObjectName("PorttextEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.PorttextEdit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.Communitylabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.Communitylabel.setObjectName("Communitylabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Communitylabel)
        self.CommunitytextEdit = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.CommunitytextEdit.setObjectName("CommunitytextEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.CommunitytextEdit)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        self.VErsionSNMPlabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.VErsionSNMPlabel.setObjectName("VErsionSNMPlabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.VErsionSNMPlabel)
        self.SNMPtextEdit = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.SNMPtextEdit.setObjectName("SNMPtextEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.SNMPtextEdit)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(8, QtWidgets.QFormLayout.LabelRole, spacerItem4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        bCancel=self.pushButtonCancel = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        bCancel.clicked.connect(self.onClick)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButtonCancel)
        self.pushButtonADD = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButtonADD.setObjectName("pushButtonADD")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pushButtonADD)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.formLayout.setLayout(8, QtWidgets.QFormLayout.FieldRole, self.verticalLayout)
        self.sasasas.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(80, 20, 261, 31))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.IPhostLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.IPhostLabel.setObjectName("IPhostLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.IPhostLabel)
        self.IPHosttextEdit = QtWidgets.QTextEdit(self.formLayoutWidget_3)
        self.IPHosttextEdit.setObjectName("IPHosttextEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.IPHosttextEdit)
        self.pushButtonDeleteDevice = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonDeleteDevice.setGeometry(QtCore.QRect(230, 60, 108, 23))
        self.pushButtonDeleteDevice.setObjectName("pushButtonDeleteDevice")
        self.sasasas.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_4)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(410, 30, 121, 121))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.tab_4)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(30, 30, 351, 191))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.IPlabelInfo = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.IPlabelInfo.setObjectName("IPlabelInfo")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.IPlabelInfo)
        self.portLabelInfo = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.portLabelInfo.setObjectName("portLabelInfo")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.portLabelInfo)
        self.CommunityLabelInfo = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.CommunityLabelInfo.setObjectName("CommunityLabelInfo")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.CommunityLabelInfo)
        self.systemLabelInfo = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.systemLabelInfo.setObjectName("systemLabelInfo")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.systemLabelInfo)
        self.contactLabelInfo = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.contactLabelInfo.setObjectName("contactLabelInfo")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.contactLabelInfo)
        self.localLabelInfo = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.localLabelInfo.setObjectName("localLabelInfo")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.localLabelInfo)
        self.IPTextEditInfo = QtWidgets.QTextEdit(self.formLayoutWidget_4)
        self.IPTextEditInfo.setObjectName("IPTextEditInfo")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.IPTextEditInfo)
        self.portTextEditInfo = QtWidgets.QTextEdit(self.formLayoutWidget_4)
        self.portTextEditInfo.setObjectName("portTextEditInfo")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.portTextEditInfo)
        self.CommunityTextEditInfo = QtWidgets.QTextEdit(self.formLayoutWidget_4)
        self.CommunityTextEditInfo.setObjectName("CommunityTextEditInfo")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.CommunityTextEditInfo)
        self.systemPlainTextEditInfo = QtWidgets.QPlainTextEdit(self.formLayoutWidget_4)
        self.systemPlainTextEditInfo.setObjectName("systemPlainTextEditInfo")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.systemPlainTextEditInfo)
        self.contactTextEditInfo = QtWidgets.QTextEdit(self.formLayoutWidget_4)
        self.contactTextEditInfo.setObjectName("contactTextEditInfo")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.contactTextEditInfo)
        self.locationTextEditInfo = QtWidgets.QTextEdit(self.formLayoutWidget_4)
        self.locationTextEditInfo.setObjectName("locationTextEditInfo")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.locationTextEditInfo)
        self.sasasas.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 853, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.sasasas.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    @pyqtSlot()
    def onClick(self):
        print("el boton de se apreto!!")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SNMP monitor"))
        self.sasasas.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>asasa</p></body></html>"))
        self.sasasas.setTabText(self.sasasas.indexOf(self.tab), _translate("MainWindow", "devices"))
        self.IPlabel.setText(_translate("MainWindow", "IP"))
        self.Portlabel.setText(_translate("MainWindow", "Port"))
        self.Communitylabel.setText(_translate("MainWindow", "Community"))
        self.VErsionSNMPlabel.setText(_translate("MainWindow", "Version snmp"))
        self.pushButtonCancel.setText(_translate("MainWindow", "  cancel   "))
        self.pushButtonADD.setText(_translate("MainWindow", "add"))
        self.sasasas.setTabText(self.sasasas.indexOf(self.tab_3), _translate("MainWindow", "Add device"))
        self.IPhostLabel.setText(_translate("MainWindow", "Ip host"))
        self.pushButtonDeleteDevice.setText(_translate("MainWindow", "delete"))
        self.sasasas.setTabText(self.sasasas.indexOf(self.tab_2), _translate("MainWindow", "Delete device"))
        self.IPlabelInfo.setText(_translate("MainWindow", "IP host"))
        self.portLabelInfo.setText(_translate("MainWindow", "port"))
        self.CommunityLabelInfo.setText(_translate("MainWindow", "Community"))
        self.systemLabelInfo.setText(_translate("MainWindow", "Op Sistem"))
        self.contactLabelInfo.setText(_translate("MainWindow", "Contact"))
        self.localLabelInfo.setText(_translate("MainWindow", "Location"))
        self.sasasas.setTabText(self.sasasas.indexOf(self.tab_4), _translate("MainWindow", "info device"))


